### ISSUE TITLE
diff-images are not embedded in Allure reports.

### ISSUE THREAD

**Issue by AugustineAutoGit** [stracker-phil/codeceptjs-pixelmatchhelper#8]
Actual: The diff-images are not embedded in Allure reports. Only Wrapped Error message is displayed
Expected:  The diff-images should be embedded in Allure reports

<img width="793" alt="Screenshot 2024-04-16 at 2 58 26 PM" src="https://github.com/stracker-phil/codeceptjs-pixelmatchhelper/assets/62946633/63f67ca0-c5d4-4461-bb8a-b63cf5661039">

**Comment by stracker-phil** [comment]
Thanks for reporting this issue 👍 

Unfortunately, I'm not actively developing this package at the time, as I'm not using CodeceptJS in my projects.

**Comment by AugustineAutoGit** [comment]
> Thanks for reporting this issue 👍
> 
> Unfortunately, I'm not actively developing this package at the time, as I'm not using CodeceptJS in my projects.

@stracker-phil thanks for the reply.
Do you know anyone else who can work on this?
